# Generated by Django 5.0.3 on 2024-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
